services:
  auth-db:
    image: postgres:18-alpine
    container_name: gatekeeper-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gatekeeper_db
    ports:
      - "5435:5432"
    networks:
      - gatekeeper-network

  auth-redis:
    image: redis:alpine
    container_name: gatekeeper-redis
    ports:
      - "6379:6379"
    networks:
      - gatekeeper-network

networks:
  gatekeeper-network:
    driver: bridge
    name: gatekeeper-network
